### ISSUE TITLE
 fatal error: fcl/fcl.h: No such file or directory #include <fcl/fcl.h>

### ISSUE THREAD

**Issue by iseequeue** [robotics-ETF/RPMPLv2#3]
at step 2.5 make build an error occures  fatal error: fcl/fcl.h: No such file or directory
   12 | #include <fcl/fcl.h>
does fcl library contains in your dependencies and if not, how can i fix this problem?

**Comment by roboticsETF** [comment]
Did you install fcl library?

First, do update with `sudo apt-get update -y`

Then install it with `sudo apt-get install -y libfcl-dev`
