### ISSUE TITLE
need some help at make build step

### ISSUE THREAD

**Issue by iseequeue** [robotics-ETF/RPMPLv2#4]
CMake Error at CMakeLists.txt:47 (find_package):
  By not providing "Findfcl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fcl", but
  CMake did not find one.

  Could not find a package configuration file provided by "fcl" (requested
  version 0.7) with any of the following names:

    fclConfig.cmake
    fcl-config.cmake

  Add the installation prefix of "fcl" to CMAKE_PREFIX_PATH or set "fcl_DIR"
  to a directory containing one of the above files.  If "fcl" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by roboticsETF** [comment]
I think you have not installed fcl library on your machine.

**Comment by iseequeue** [comment]
thank you very much, that fixed everything.
